name: CI Compile Tests

on:
    workflow_dispatch:
    pull_request:

env:
    ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    ARBISCAN_API_KEY: ${{ secrets.ARBISCAN_API_KEY }}
    L1_ALCHEMY_API_KEY: ${{ secrets.L1_ALCHEMY_API_KEY }}
    L2_ALCHEMY_API_KEY: ${{ secrets.L2_ALCHEMY_API_KEY }}
    TESTNET_PRIVATE_KEY: ${{ secrets.CI_WALLET_TESTNET_PRIVATE_KEY }}
    MAINNET_PRIVATE_KEY: ${{ secrets.CI_WALLET_MAINNET_PRIVATE_KEY }}

jobs:
    compileTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Run yarn to setup
              run: yarn

            - name: Run hardhat compile
              run: npx hardhat compile --force

            - name: Run mocha
              run: npx hardhat test
